Migrate to Go modules
This project currently fails to compile due to breaking changes in v2 of
github.com/urfave/cli:

    cmd/speakeasy/main.go:23:19: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
    cmd/speakeasy/main.go:29:15: cannot use []cli.Command literal (type []cli.Command) as type []*cli.Command in assignment

Adding the package as a module requirement allows us to pin it to v1.